server:
  port: 8000
spring:
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60
  datasource:
    oracle:
      username: root
      url: jdbc:oracle:thin:@localhost:1521:helowin
      password: root
      driver-class-name: oracle.jdbc.OracleDriver
    mysql:
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/dev
      driver-class-name: com.mysql.jdbc.Driver
# JPA配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      oracle-dialect: org.hibernate.dialect.Oracle10gDialect
      mysql-dialect: org.hibernate.dialect.MySQL8Dialect
