server:
  port: 9000
spring:
  application:
    name: mybatis-plus-multidatasource
  # 配置数据源
  datasource:
    druid:
      oracle:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:helowin
        username: root
        password: root
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: 30000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        filters: stat,wall,log4j2
        onnectionProperties=druid: stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      mysql:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/dev?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: 30000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        filters: stat,wall,log4j2
        onnectionProperties=druid: stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: cn.lianxf.cloud.handler
logging:
  level:
    cn.lianxf.cloud.mapper: debug
