server:
  port: 8000
spring:
  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: false
    atomikos:
      datasource:
        oracle:
          unique-resource-name: oracleDataSource
          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          xa-properties:
            driverClassName: oracle.jdbc.OracleDriver
            username: root
            url: jdbc:oracle:thin:@localhost:1521:helowin
            password: "root"
        mysql:
          unique-resource-name: mysqlDataSource
          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          xa-properties:
            driverClassName: com.mysql.cj.jdbc.Driver
            username: root
            url: jdbc:mysql://localhost:3307/dev?useUnicode=true&characterEncoding=utf-8
            password: "root"
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: cn.lianxf.cloud.handler
logging:
  level:
    cn.lianxf.cloud.mapper: debug
