server:
  port: 9000
spring:
  application:
    name: data-jpa-multidatasource
  # 配置数据源
  datasource:
    druid:
      oracle:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:helowin
        username: root
        password: root
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: 30000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        filters: stat,wall,log4j2
        onnectionProperties=druid: stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      mysql:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/dev?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: 30000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        filters: stat,wall,log4j2
        onnectionProperties=druid: stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# JPA配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      oracle-dialect: org.hibernate.dialect.Oracle10gDialect
      mysql-dialect: org.hibernate.dialect.MySQL8Dialect
