spring:
  application:
    name: api-consumer
management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
#logging:
#  level:
#    root: debug
feign:
  # 开启压缩
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
