server:
    port: 8080
spring:
    application:
        name: data-jpa-demo
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:helowin
        username: root
        password: root

    jpa:
        database: oracle
        properties:
            hibernate:
                dialect: org.hibernate.dialect.Oracle10gDialect
        hibernate:
            ddl-auto: update
        show-sql: true
